### ISSUE TITLE
refactor IRT `EVALUATION` for the `edm4hep` update

### ISSUE THREAD

**Issue by c-dilks** [eic/irt#1]
Since the data model has changed, we need to refactor some of the `evaluation` code. Things to do include:
- update our usage of `eic::Index`, since we now use PODIO relations instead
- should we use `edm4hep::MCParticle` to replace `dd4pod::Geant4Particle`?
- how to match `ReconstructedParticle` to the MC generated particle? we no longer have `mcID`, do we need to add a relation in `eicd`?

**Comment by wdconinc** [comment]
2. `edm4hep::MCParticle` replaces `dd4pod::Geant4Particle` indeed.
3. Algorithms (if running based on MC, for some algorithms optionally) which create e.g. `EcalEndcapNClusters`, will also create corresponding associations, e.g. `EcalEndcapNClustersAssoc`. If you use clusters from a previous algorithms, you can use the associations too to figure out the connection to MC (note that if you require the associations you would only be able to run on MC). If you produce `ReconstructedParticle` yourself, you can produce associations too, but you do not have to. See https://eicweb.phy.anl.gov/EIC/juggler/-/merge_requests/432/diffs for the transition from `eic::Index` to associations in some of the relevant juggler algorithms.
