### ISSUE TITLE
File not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by DraTeots** [eic/irt#28]
Currently IRT library is linked in eicrecon like: 

```cmake
    plugin_include_directories(${PLUGIN_NAME} SYSTEM PUBLIC ${IRT_INCLUDE_DIR})
    plugin_link_libraries(${PLUGIN_NAME} IRT)
```

The problem here, is that if IRT library is not installed in system folder and LD_LIBRARY_PATH is not provided, it is not found at runtime. Following what is a good practice for cmake, I changed that to: 

```cmake
    find_library(IRT_LIBRARY IRT PATHS ${IRT_DIR}/..)
    message("{IRT_INCLUDE_DIR} ${IRT_INCLUDE_DIR}")
    message("{IRT_LIBRARY} ${IRT_LIBRARY}")
    plugin_include_directories(${PLUGIN_NAME} SYSTEM PUBLIC ${IRT_INCLUDE_DIR})
    plugin_link_libraries(${PLUGIN_NAME} ${IRT_LIBRARY})
```

Now, surprisingly, the code doesn't compile because: 

```
/include/IRT/CherenkovDetectorCollection.h:14:10: error: 'BitMask.h' file not found with <angled> include; use "quotes" instead
#include <BitMask.h>

# and many others like this
```

> I checked that ${IRT_LIBRARY} is a full path to a valid library now

That confuses me a lot, why `plugin_link_libraries(${PLUGIN_NAME} IRT)` and `plugin_link_libraries(${PLUGIN_NAME} ${IRT_LIBRARY})` produces so drastic difference. But! [following C++ standard](https://stackoverflow.com/questions/3162030/difference-between-angle-bracket-and-double-quotes-while-including-heade#:~:text=When%20you%20use%20angle%20brackets,search%20the%20include%20path%20list.) BitMask.h and other files indeed should be enclosed in quotes

```cpp
#include <IRT/BitMask.h'>
// or
#include "BitMask.h"   // for headers in the same directory
```

Files with errors: 

[irt_build_log.txt](https://github.com/eic/irt/files/10904983/irt_build_log.txt)

**Comment by c-dilks** [comment]
@DraTeots let me know if #29 fixes this issue. Meanwhile I will check to make sure EICrecon's usage of IRT still works.
